### ISSUE TITLE
Alternative problem types

### ISSUE THREAD

**Issue by tdstoff** [civilwargeeky/CEA_Wrap#5]
Hi @civilwargeeky, thanks for this package, it's a great upgrade from 'manual' CEA runs. I'm wondering about running other problem types besides h/p, rockets, and detonations as you have listed in the README and defined in the package. In my case, I really need to experiment with some simple T/p problems like this:

```
problem tp p(atm)=1,t(k)=2350
reac
name AL  wt%= 50.
name Air wt%= 50.
output siunits massf
end
```

Do you already have thoughts about the best way to add the other problem types? I didn't understand any way to do that from the README. I tried creating another class in CEA.py called `TPProblem` based on `HPProblem`, but didn't fully grasp how to get the inputs parsed correctly for the .inp file. For T/p problems, CEA wants a single pressure and temperature in the input file and doesn't like having it set material-wise like the `HPProblem` class does, e.g.

```
fuel=AL wt=2.00000  t,k=298.15000
ox=Air wt=98.00000  t,k=298.15000
```

**Comment by civilwargeeky** [comment]
Hello! I'm glad you've been enjoying the program, and I apologize for not looking at this sooner.
It looks like a TP problem is pretty similar to an HP problem, except the differences you pointed out in the input. To solve those issues, we just need to modify how the Material objects report their CEA string to not include temperature, and modify how the TP problem reports its prefix string to include temperature. I will add this to a later release, but you can edit your own CEA.py file right now to include the following code, and it should work for you. Let me know if this is inaccurate or if you run into any issues.
```python

class TPMaterial(Material):
  def __init__(self, parent):
    p = parent
    self.parent = p
    self.output_type = self.parent.output_type
    super().__init__(p.name, p.temp, p.wt_percent, p.mols, p.chemical_composition, p.hf)
  
  def is_fuel(self):
    return self.parent.is_fuel()
  
  def get_CEA_str(self) -> str:
    # This is just copy-paste from Material, but I removed the temperature-writing from the code
    name, ratio = "wt" if self.wt_percent is not None else "mol", self.wt_percent if self.wt_percent is not None else self.mols
    if ratio < 0:
      raise ValueError("Cannot have {} with <0 {} percent!".format(self.name, name))
    elif ratio == 0: # This allows us to not include materials that are set to 0 percent
      return ""
    else:
      string = "   {}={} {}={:0.5f}".format(self.output_type, self.name, name, ratio)
      if self.hf:
        string += " h,kj/mol={:0.5f}".format(self.hf)
      if self.chemical_composition:
        string += " " + self.chemical_composition
      return string + " \n" 

class TPProblem(HPProblem):
  problem_type = "tp"
  
  def __init__(self, *args, 
    temperature=298, # Reaction temperature, in Kelvin
    **kwargs
  ):
    super().__init__(*args, **kwargs)
      
    self.temperature = temperature
  
  def get_prefix_string(self):
    toRet = []
    toRet.append("{}".format(self.problem_type))
    toRet.append("   p({}) = {:0.5f}".format(self.pressure_units, self.pressure))
    toRet.append("   t(k) = {:0.5f}".format(self.temperature)) # Report temperature here
    return "\n".join(toRet) + "\n"
  
  def make_input_file(self, material_list: List[Material]): # chamber conditions and materials list
    # Here we convert all the materials to TPMaterials before calling the main function, so that each one doesn't report temperature
    new_material_list = [TPMaterial(material) for material in material_list]
    return super().make_input_file(new_material_list)

```

**Comment by civilwargeeky** [comment]
Also, I realized I accidentally removed the O/F portion of the input string, which you didn't have in your example, but the function should be fixed to look like:
```
  def get_prefix_string(self):
    toRet = []
    toRet.append("{}".format(self.problem_type))
    toRet.append("   p({}) = {:0.5f}".format(self.pressure_units, self.pressure))
    toRet.append("   t(k) = {:0.5f}".format(self.temperature))
    toRet.append("   {} = {:0.5f}".format(self.ratio_name, self.ratio_value))
    return "\n".join(toRet) + "\n"
```

And I didn't know that you could exclude that portion to just use basic weight percents! That could be a useful feature in the program going forward. Then we wouldn't need to have set_absolute_o_f as a function!

**Comment by tdstoff** [comment]
Sure, that makes sense that you had to make the material object, I had missed that. Just tried it out and it works. Thanks!
